# Generated by Django 5.0.1 on 2025-11-17 14:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('matches', '0002_initial'),
        ('ratings', '0002_initial'),
        ('tournaments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='organizer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organized_tournaments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tournament',
            name='season',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tournaments', to='ratings.season'),
        ),
        migrations.AddField(
            model_name='tournamentbracket',
            name='loser_advances_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loser_source_brackets', to='tournaments.tournamentbracket'),
        ),
        migrations.AddField(
            model_name='tournamentbracket',
            name='match',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tournament_bracket', to='matches.match'),
        ),
        migrations.AddField(
            model_name='tournamentbracket',
            name='player1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bracket_as_player1', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tournamentbracket',
            name='player2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bracket_as_player2', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tournamentbracket',
            name='tournament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brackets', to='tournaments.tournament'),
        ),
        migrations.AddField(
            model_name='tournamentbracket',
            name='winner_advances_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_brackets', to='tournaments.tournamentbracket'),
        ),
        migrations.AddField(
            model_name='tournamentgroup',
            name='tournament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='tournaments.tournament'),
        ),
        migrations.AddField(
            model_name='tournamentgroupstanding',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='standings', to='tournaments.tournamentgroup'),
        ),
        migrations.AddField(
            model_name='tournamentgroupstanding',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_standings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tournamentparticipant',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tournament_participations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tournamentparticipant',
            name='tournament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='tournaments.tournament'),
        ),
        migrations.AddField(
            model_name='tournamentround',
            name='tournament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rounds', to='tournaments.tournament'),
        ),
        migrations.AddField(
            model_name='tournamentbracket',
            name='round',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brackets', to='tournaments.tournamentround'),
        ),
        migrations.AlterUniqueTogether(
            name='tournamentgroup',
            unique_together={('tournament', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='tournamentgroupstanding',
            unique_together={('group', 'player')},
        ),
        migrations.AlterUniqueTogether(
            name='tournamentparticipant',
            unique_together={('tournament', 'player')},
        ),
        migrations.AlterUniqueTogether(
            name='tournamentround',
            unique_together={('tournament', 'round_number')},
        ),
        migrations.AlterUniqueTogether(
            name='tournamentbracket',
            unique_together={('tournament', 'round', 'bracket_position')},
        ),
    ]
