# Generated by Django 5.0.1 on 2026-02-11 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='registration_closed_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when registration was manually closed by admin', null=True),
        ),
        migrations.AddField(
            model_name='tournament',
            name='registration_mode',
            field=models.CharField(choices=[('AUTOMATIC', 'Automatic (deadline-based)'), ('MANUAL', 'Manual (admin closes)')], default='AUTOMATIC', help_text='AUTOMATIC: closes at deadline, MANUAL: admin closes manually', max_length=20),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='registration_deadline',
            field=models.DateTimeField(blank=True, help_text='Required for AUTOMATIC mode, optional for MANUAL mode', null=True),
        ),
    ]
