# Generated by Django 5.0.1 on 2026-03-05 23:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0003_tournament_registration_closed_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='awards_distributed',
            field=models.BooleanField(default=False, help_text='True after distribute-awards has been run; blocks re-distribution until reset'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='prize_label',
            field=models.CharField(blank=True, help_text='Display label for the prize shown on the tournament card (e.g. "₵500 Cash Prize")', max_length=100),
        ),
        migrations.CreateModel(
            name='AwardTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tier_type', models.CharField(choices=[('POSITION', 'Position'), ('ALL_PARTICIPANTS', 'All Participants'), ('SPECIFIC_USER', 'Specific User')], max_length=20)),
                ('position', models.PositiveIntegerField(blank=True, help_text='Final rank that triggers this award. Required for POSITION type.', null=True)),
                ('points', models.PositiveIntegerField(help_text="Number of points credited to the player's current_rating")),
                ('label', models.CharField(blank=True, help_text='Optional display label (e.g. "Champion", "Fair Play Award")', max_length=100)),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='award_tiers', to='tournaments.tournament')),
                ('user', models.ForeignKey(blank=True, help_text='Target player. Required for SPECIFIC_USER type.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='specific_award_tiers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['tier_type', 'position'],
            },
        ),
        migrations.CreateModel(
            name='PlayerAward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points_awarded', models.PositiveIntegerField()),
                ('awarded_at', models.DateTimeField(auto_now_add=True)),
                ('award_tier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='player_awards', to='tournaments.awardtier')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_awards', to=settings.AUTH_USER_MODEL)),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_awards', to='tournaments.tournament')),
            ],
            options={
                'ordering': ['-awarded_at'],
            },
        ),
    ]
