# Generated by Django 5.0.1 on 2026-03-06 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0004_award_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='is_public',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='tournament',
            name='location',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
    ]
