# Generated by Django 5.0.1 on 2026-03-12 22:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0006_tournament_deleted_at_tournament_deleted_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='match_format',
            field=models.CharField(choices=[('BEST_OF_3', 'Best of 3'), ('BEST_OF_5', 'Best of 5'), ('BEST_OF_7', 'Best of 7')], default='BEST_OF_3', help_text='Default match format (Best of 3/5/7) for all matches in this tournament', max_length=20),
        ),
        migrations.AddField(
            model_name='tournamentbracket',
            name='winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bracket_wins', to=settings.AUTH_USER_MODEL),
        ),
    ]
