# Generated by Django 5.0.1 on 2026-03-27 21:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0008_tournamentroundformat'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='awardtier',
            constraint=models.UniqueConstraint(condition=models.Q(('position__isnull', False)), fields=('tournament', 'position'), name='unique_position_rank_per_tournament'),
        ),
    ]
