# Generated by Django 5.0.1 on 2025-11-17 14:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('challenges', '0001_initial'),
        ('ratings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='challenged',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='challenges_received', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='challenge',
            name='challenger',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='challenges_sent', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='challenge',
            name='season',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='challenges', to='ratings.season'),
        ),
        migrations.AddField(
            model_name='challengehistory',
            name='season',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='challenge_history', to='ratings.season'),
        ),
        migrations.AddField(
            model_name='challengehistory',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='challenge_history', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='challenge',
            index=models.Index(fields=['challenger', 'status'], name='challenges__challen_79d5a0_idx'),
        ),
        migrations.AddIndex(
            model_name='challenge',
            index=models.Index(fields=['challenged', 'status'], name='challenges__challen_96a9bf_idx'),
        ),
        migrations.AddIndex(
            model_name='challenge',
            index=models.Index(fields=['season'], name='challenges__season__d05500_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='challengehistory',
            unique_together={('user', 'season')},
        ),
    ]
