# Generated by Django 5.0.1 on 2025-11-28 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='format_value',
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name='challenge',
            name='match_format',
            field=models.CharField(choices=[('BEST_OF', 'Best of'), ('RACE_TO', 'Race to')], default='BEST_OF', max_length=20),
        ),
        migrations.AddField(
            model_name='challenge',
            name='match_type',
            field=models.CharField(choices=[('DUEL', 'Duel'), ('TRAINING', 'Training')], default='DUEL', max_length=20),
        ),
    ]
