# Generated by Django 5.0.1 on 2025-11-24 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('PLAYER', 'Player'), ('REFEREE', 'Referee')], default='PLAYER', max_length=10),
        ),
    ]
