# Generated by Django 5.0.1 on 2025-11-27 15:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_rating', models.IntegerField(default=1000)),
                ('highest_rating', models.IntegerField(default=1000)),
                ('league', models.CharField(choices=[('AMATEUR', 'Amateur'), ('PRO', 'Professional')], default='AMATEUR', max_length=20)),
                ('total_matches', models.IntegerField(default=0)),
                ('wins', models.IntegerField(default=0)),
                ('losses', models.IntegerField(default=0)),
                ('win_streak', models.IntegerField(default=0)),
                ('longest_win_streak', models.IntegerField(default=0)),
                ('is_active_player', models.BooleanField(default=True)),
                ('last_match_date', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='player_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SuperAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_level', models.CharField(choices=[('SUPER', 'Super Admin'), ('MODERATOR', 'Moderator')], default='SUPER', max_length=20)),
                ('department', models.CharField(blank=True, max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='admin_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
