# Generated by Django 5.0.1 on 2025-11-27 15:08

from django.db import migrations

def move_user_data(apps, schema_editor):
    User = apps.get_model('users', 'User')
    PlayerProfile = apps.get_model('users', 'PlayerProfile')
    SuperAdmin = apps.get_model('users', 'SuperAdmin')

    for user in User.objects.all():
        # Create PlayerProfile for everyone (since everyone can play/referee)
        PlayerProfile.objects.create(
            user=user,
            current_rating=user.current_rating,
            highest_rating=user.highest_rating,
            league=user.league,
            total_matches=user.total_matches,
            wins=user.wins,
            losses=user.losses,
            win_streak=user.win_streak,
            longest_win_streak=user.longest_win_streak,
            is_active_player=user.is_active_player,
            last_match_date=user.last_match_date
        )

        # Create SuperAdmin profile for Admins
        if user.role == 'ADMIN':
            SuperAdmin.objects.create(
                user=user,
                admin_level='SUPER'
            )

class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_playerprofile_superadmin'),
    ]

    operations = [
        migrations.RunPython(move_user_data),
    ]
