# Generated by Django 5.0.1 on 2025-11-27 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_move_user_data'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['-date_joined']},
        ),
        migrations.RemoveIndex(
            model_name='user',
            name='users_user_current_6a84ac_idx',
        ),
        migrations.RemoveIndex(
            model_name='user',
            name='users_user_league_f2971f_idx',
        ),
        migrations.RemoveField(
            model_name='user',
            name='current_rating',
        ),
        migrations.RemoveField(
            model_name='user',
            name='highest_rating',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_active_player',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_match_date',
        ),
        migrations.RemoveField(
            model_name='user',
            name='league',
        ),
        migrations.RemoveField(
            model_name='user',
            name='longest_win_streak',
        ),
        migrations.RemoveField(
            model_name='user',
            name='losses',
        ),
        migrations.RemoveField(
            model_name='user',
            name='total_matches',
        ),
        migrations.RemoveField(
            model_name='user',
            name='win_streak',
        ),
        migrations.RemoveField(
            model_name='user',
            name='wins',
        ),
    ]
