# Generated by Django 5.0.1 on 2026-03-12 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='table_number',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
