# Generated by Django 5.0.1 on 2026-03-22 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0003_add_table_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='target_score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='match_format',
            field=models.CharField(choices=[('BEST_OF_3', 'Best of 3'), ('BEST_OF_5', 'Best of 5'), ('BEST_OF_7', 'Best of 7'), ('RACE_TO_5', 'Race to 5'), ('RACE_TO_11', 'Race to 11'), ('RACE_TO_21', 'Race to 21')], default='BEST_OF_3', max_length=20),
        ),
    ]
