# Generated by Django 5.0.1 on 2025-11-17 14:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('matches', '0002_initial'),
        ('ratings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='leaguestanding',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='league_standings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ratinghistory',
            name='match',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rating_changes', to='matches.match'),
        ),
        migrations.AddField(
            model_name='ratinghistory',
            name='opponent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opponent_rating_history', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ratinghistory',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rating_history', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ratinghistory',
            name='season',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rating_changes', to='ratings.season'),
        ),
        migrations.AddField(
            model_name='leaguestanding',
            name='season',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='league_standings', to='ratings.season'),
        ),
        migrations.AddIndex(
            model_name='ratinghistory',
            index=models.Index(fields=['user', '-created_at'], name='ratings_rat_user_id_7443d3_idx'),
        ),
        migrations.AddIndex(
            model_name='ratinghistory',
            index=models.Index(fields=['season'], name='ratings_rat_season__0b43db_idx'),
        ),
        migrations.AddIndex(
            model_name='leaguestanding',
            index=models.Index(fields=['season', 'league', 'rank'], name='ratings_lea_season__33eea3_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='leaguestanding',
            unique_together={('user', 'season')},
        ),
    ]
