# Generated by Django 5.0.1 on 2026-03-12 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0004_season_deleted_at_season_deleted_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='season',
            name='format',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='season',
            name='lead_organizer',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='season',
            name='player_cap',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='season',
            name='prize_pool',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='season',
            name='region',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='season',
            name='ruleset',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
