# Generated by Django 5.0.1 on 2026-03-13 20:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0005_season_metadata_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaguestanding',
            name='points',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='PointConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('win_points', models.IntegerField(default=3)),
                ('loss_points', models.IntegerField(default=0)),
                ('draw_points', models.IntegerField(default=1)),
                ('walkover_points', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('season', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='point_config', to='ratings.season')),
            ],
        ),
    ]
