# Generated by Django 5.0.1 on 2026-03-13 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0006_leaguestanding_points_pointconfig'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leaguestanding',
            name='points',
        ),
        migrations.DeleteModel(
            name='PointConfig',
        ),
    ]
